### ISSUE TITLE
BGDI SEGFAULT Executing SORMAKER.DAT after buying it at the shop.

### ISSUE THREAD

**Issue by Kelvfimer** [christianhaitian/bennugd-monolithic#1]
Hello

I'm getting a segfault when executing => EmuELEC:~/roms/ports/sorr # bgdi SorMaker.dat
INFO: Called set_mode with 320x240x0
INFO: set_title(SorMaker Editor v1.0 - Bombergames Soft 2011)
INFO: Called set_mode with 320x240x0
INFO: Called set_fps(60, 4)
INFO: Loading mod/sormaker/sormaker.fpg
INFO: Result: 0
INFO: Loading mod/sormaker/item.fpg
INFO: Result: 1
INFO: Loading mod/sormaker/objeto.fpg
INFO: Result: 2
INFO: Wondering if file_exists(savegame/savegame.sor) -> 1
INFO: Loading mod/sormaker/fuente.fpg
INFO: Result: 3
INFO: Loading mod/sormaker/general.fpg
INFO: Result: 4
INFO: Loading mod/sormaker/lista_sormaker.fpg
INFO: Result: 5
Segmentation fault

If the SORMaker item is not bought at the shop yet, it's working fine displaying the image prompting to buy it at the shop. So I guess it's not an emuelec issue.

The issue is happening inside the game selecting sormaker and executing it manually.

Pls can you help on this?

thx!!!
Kind Regards

**Comment by christianhaitian** [comment]
Not something i’m capable of addressing.  I only modified this enough to just play the main SorR game.  Unless this is something that someone like isage(https://github.com/isage/sorr-vita) has addressed somehow, understanding even where to look to address this is beyond my capability with this.
